### ISSUE TITLE
th() and thUri() empty

### ISSUE THREAD

**Issue by carstengrimm** [tobimori/kirby-thumbhash#1]
i have been using placeholderuri (the alternative you mention in your documentation) and it has been working mostly fine. However i wanted to give thumbhash as well as blurhash a chance and tried both. According to your docs, thumbhash is a bit more flexible so i have added it to my plugins via composer.

On both it seems like the methods

- thUri
- th
- thumbhash
- thumbhashUri

seems to return empty values.
in my image (webp) but also other formats, i am passing the image to snippets, within the snippet i am doing srcset and all sorts of other things, with a lazyload but it seems the src value is empty.

```
//... Bit more stuff like $px
<picture>
<?php if(!$site->disablewebp()->bool()): ?>
    <source     
        data-srcset="<?= $image->focusSrcset(option('cg.landing.focussrcset.square.webp')); ?>"
        data-sizes="auto" type="image/webp"
    >
<?php endif ?>
    <source     
        data-srcset="<?= $image->focusSrcset(option('cg.landing.focussrcset.square.jpeg')); ?>"
        data-sizes="auto" type="image/jpeg"
    >
<img 
    class="lazyload blur-up aspect-square <?= e(isset($border),' border ') ?> <?= e(isset($rounded),' rounded-full ') ?> <?= $c ?>" 
    src="<?= $image->thUri(['ratio' => 1,'transparent' => true]) ?>" 
    <?php if($site->srcplaceholder()->bool()): ?>
        <?php /* src="<?= $image->th(['ratio' => 1,'transparent' => true]) ?>" */ ?>
    <?php else: ?>
    src="<?= $image->focusCrop($px,$px,['quality' => 10])->url() ?>" 
    <?php endif ?>
    data-srcset="<?= $image->focusSrcset(option('cg.landing.focussrcset.square')); ?>"
    data-sizes="auto" 
    alt="<?= $image->alt() ?>" 
    width="<?= $px ?>" 
    height="<?= $px ?>"
>
</picture>
```

PHP 8.2.6.
Kirby 3.9.5
GD and everything enabled.
Local Testing.

**Comment by tobimori** [comment]
Can you try to provide a reproducible example (check if this happens with a plainkit and your images)? I can then look into it further. The plugin should be fine with the following formats:
`imagecreatefromstring() returns an image identifier representing the image obtained from the given data. These types will be automatically detected if your build of PHP supports them: JPEG, PNG, GIF, BMP, WBMP, GD2, and WEBP.`

**Comment by carstengrimm** [comment]
I've just installed a plainkit on my local server and added thumbhash as well as blurhash via composer, it seems in this minimalistic test that it is working...
both my testserver and (live-test)server does not have problems with image manipulation in any way.

seeing in plain kit it's working, there must be another reason other than the server...
i am using a few other plugins like focus Crop, but it seems that still lets it work in the plainkit


```
<script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.3.2/lazysizes.min.js"></script>
<h1><?= $page->title() ?></h1>

<?php if($image = $page->file('test.webp')): ?>
    <img src="<?= $image->blurhashUri(3/2,['ratio' => 1,'transparent' => true]) ?>" data-sizes="auto" data-src="<?= $image->url() ?>" class="lazyload" alt="" width="150">
<?php endif ?>
```

will have to investigate further...
