### ISSUE TITLE
Wrong default options for `cache`

### ISSUE THREAD

**Issue by hirasso** [tobimori/kirby-thumbhash#3]
Hi there! I just noticed these default plugin options in the plugin's source code:

https://github.com/tobimori/kirby-thumbhash/blob/cfc48966eb901d3b6a80142385ca70415d697073/index.php#L29-L31

While the documentation states that both these options [should be`true` by default](https://github.com/tobimori/kirby-thumbhash#options-1).

**Comment by tobimori** [comment]
LOL you're right. never noticed it. guess i've been running thumbhash without cache in production all the time 🙈

**Comment by tobimori** [comment]
will be fixed in the next release
